module(load="imfile")
module(load="mmjsonparse")

global(workDirectory="/work")

input(
  type="imfile"
  File="/var/log/logstorm/app.log"
  Tag="logstorm"
  Facility="local0"
  Severity="info"
  PersistStateInterval="100"
)

ruleset(name="logstorm-forward") {
  action(type="mmjsonparse")
  action(
    type="omfwd"
    target="nifi"
    port="5140"
    protocol="udp"
    Template="RSYSLOG_SyslogProtocol23Format"
    action.resumeRetryCount="-1"
  )
}

if $programname == "logstorm" then {
  call logstorm-forward
  stop
}
